### ISSUE TITLE
Implementation vs paper

### ISSUE THREAD

**Issue by victorherbemontagne** [openai/glow#34]
Hi,

First of all, thanks for this amazing work, it has been a pleasure to dive in the paper !

Now more precisely, when looking at the implementation and the implementation of the actnorm module, I can't understand the choice made considering the paper.
In the paper you state that you used a affine transformation of the activation with parameters s and b.
![image](https://user-images.githubusercontent.com/20753024/43210446-6f6d5088-902f-11e8-96e3-a34b5fb2a8fd.png)

But in the implementation it seems to first add the bias b: `x = x + b`(with [actnorm_center](https://github.com/openai/glow/blob/a113222f642c5ae02fce41f954eac0b99210c6d1/tfops.py#L71)), then multiply by s: `x =  s * (x+b)` (with [actnorm_scale](https://github.com/openai/glow/blob/a113222f642c5ae02fce41f954eac0b99210c6d1/tfops.py#L117))

You reverse the code when reverse = True but I feel this might be the opposite. 

I surely miss something  as you manage to train the model but I am curious about this choice.

Do I miss something?

Thank you in advance for your help !

Victor

**Comment by prafullasd** [comment]
Thanks Victor! :) You're right, we first centre the activations to 0 mean, then scale them to unit variance, we'll update the paper accordingly.
In terms of learning though the formulations are equivalent, since `x = s * (x + b) = s * x + (s * b) = s * x + b'`, where `b'` is the new bias. Note the loss 
term `sum(log(|s|))` prevents values in `s` from becoming 0.
